### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by xnbx2012** [ColinTree/extension-builder#12]
Use [http://bot.colintree.cn:8048](http://bot.colintree.cn:8048)  to build an extension failed for many times.I've tried to build with GitHub Repo and zip file.Perhaps it's because I request a pr, if it's exactly my false,I would like to say sorry here and hope colintree can fix it or undo the change.Thanks and SORRY!

**Comment by ColinTree** [comment]
What's the error message? You may give me the jobId so that I can view the log (before the server is re-deployed)

**Comment by ColinTree** [comment]
Just guessing, did you configured your extension package via `builder-config.json`?

**Comment by ColinTree** [comment]
(That was a mistake, sorry

**Comment by xnbx2012** [comment]
Job Id:ytCEp3

**Comment by xnbx2012** [comment]
> Just guessing, did you configured your extension package via `builder-config.json`?

I failed when I use the example Github repo

**Comment by ColinTree** [comment]
There was a bug that error message is not shown when failed, and I had fixed it.
Now I can see there is an issue about appinventor version on server

**Comment by ColinTree** [comment]
Fixed by 77b9fc93f96bf04a66e8b7be99b815fbc3b72a5c, thanks for reporting
